controller_list:
  - name: arm_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - rotation_joint
      - lower_joint
      - mid_joint
      - upper_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint