arm:  
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - rotation_joint
      - lower_joint
      - mid_joint
      - upper_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
  
    gains:
     rotation_joint: {p: 100.0, i: 0.1, d: 10.0, i_clamp: 0.0}
     lower_joint: {p: 100.0, i: 0.1, d: 10.0, i_clamp: 0.0}
     mid_joint: {p: 100.0, i: 0.1, d: 10.0, i_clamp: 0.0}
     upper_joint: {p: 100.0, i: 0.1, d: 10.0, i_clamp: 0.0}
     wrist1_joint: {p: 100.0, i: 0.1, d: 10.0, i_clamp: 0.0}
     wrist2_joint: {p: 100.0, i: 0.1, d: 10.0, i_clamp: 0.0}
     wrist3_joint: {p: 100.0, i: 0.1, d: 10.0, i_clamp: 0.0}

  gripper_controller: 
    type: position_controllers/GripperActionController
    joint: robotiq_85_left_knuckle_joint # or gripper_finger1_joint
    action_monitor_rate: 20
    goal_tolerance: 0.002
    max_effort: 100
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
     